### ISSUE TITLE
Support GLPI 9.5?

### ISSUE THREAD

**Issue by KongNan** [bacus99/Services#16]
Current version supports 9.4. 
I want to use it in 9.5 :)

**Comment by bacus99** [comment]
Hi

I have a new version for 9.5.4.  But there is still 1 issue I don't have time to correct (Add Service to Computer)  You can bypass by (Add Computer to Service)

Feel free to try it (Dev first recommended) and if your able, correct my issue
[services 9.5.4.zip](https://github.com/bacus99/Services/files/6264673/services.9.5.4.zip)

**Comment by FedericoFelliny** [comment]
Hello! Very interested in your plugin. How did you manage to make the plugin work (link above)? I have it installed on 9.5.6, but there are such errors.
![image](https://user-images.githubusercontent.com/92057291/136274176-13e0eae8-5eb5-4c9a-9f79-fb7762ddd746.png)

With text - Uncaught Exception Error: Class 'PluginServicesServiceStatus' not found in /var/www/glpi/plugins/services/inc/service.class.php at line 622

And something like this:
![image](https://user-images.githubusercontent.com/92057291/136274359-476e56c2-c44d-4b6e-a84e-65f44e57d200.png)


Thanx!)

**Comment by bacus99** [comment]
[services.zip](https://github.com/bacus99/Services/files/7303219/services.zip)

Hi, here's my latest version. Sorry I'm not good at maintaining GitHub.  This version is compatible 9.5.5, didn't try 9.5.6 yet.  Upgrade path may not works properly, please try in dev first

**Comment by FedericoFelliny** [comment]
@bacus99 Hello!
it seems to me that the problem is that the plugin does not create tables in DB. 
I have corrected the SQL file name to the one specified in hook.php 

![image](https://user-images.githubusercontent.com/92057291/136446831-ad50eaa0-dcb3-43ca-948d-2a7bca017465.png)


What else do you think might be the problem?

**Comment by bacus99** [comment]
I made an empty 1.3.1 file, can you test?  Dump my tables here.  Rename .sql, backup your data before


[empty-1.3.1.txt](https://github.com/bacus99/Services/files/7306792/empty-1.3.1.txt)

**Comment by FedericoFelliny** [comment]
@bacus99, I test it but, no, I still get errors(

![image](https://user-images.githubusercontent.com/92057291/136461856-e8a4ec37-e830-4049-aa9f-450ef4dea1b2.png)

Anyway, thank you for responding very quickly and not leaving me alone with this trouble)

**Comment by bacus99** [comment]
Ahhh i think the error is cause my db is prd_glpi and yours glpi...
Are you able to create the service_services manually from the script? 
--
Sent from myMail for Android Thursday, 07 October 2021, 05:06PM -04:00 from FedericoFelliny  ***@***.*** :

***@***.*** , I test it but, no, I still get errors(

**Comment by bacus99** [comment]
OK, I check my sql and it's OK

Can you run this against your DB?

CREATE TABLE IF NOT EXISTS `glpi_plugin_services_services` (
  `id` int NOT NULL,
  `entities_id` int NOT NULL DEFAULT '0',
  `is_recursive` tinyint(1) NOT NULL DEFAULT '1',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `completename2` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `backoffice` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `plugin_services_servicetypes_id` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_plugin_services_servicetypes (id)',
  `plugin_services_servicetechnics_id` int NOT NULL DEFAULT '0',
  `plugin_services_servicertos_id` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_plugin_services_serviceservertypes (id)',
  `plugin_services_servicerpos_id` int NOT NULL DEFAULT '0',
  `plugin_services_servicesupports_id` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_plugin_services_serviceserversupports (id)',
  `plugin_services_servicetiers_id` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_plugin_services_servicetiers (id)',
  `plugin_services_servicebusrisks_id` int NOT NULL DEFAULT '0',
  `plugin_services_servicebuspriorities_id` int NOT NULL DEFAULT '0',
  `dist_list` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `users_id_itowner` int DEFAULT NULL,
  `users_id_tech` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_users (id)',
  `users_id_sectech` int NOT NULL DEFAULT '0',
  `groups_id_tech` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_groups (id)',
  `users_id_bus` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_users (id)',
  `users_id_app` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_users (id)',
  `users_id_secapp` int NOT NULL DEFAULT '0',
  `suppliers_id` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_suppliers (id)',
  `manufacturers_id` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_manufacturers (id)',
  `itilcategories_id` int NOT NULL DEFAULT '0' COMMENT 'RELATION to glpi_itilcategories (id)',
  `date_mod` timestamp NULL DEFAULT NULL,
  `date_last_dr` date DEFAULT NULL,
  `date_next_dr` date DEFAULT NULL,
  `is_corp_dba_managed` int NOT NULL DEFAULT '0',
  `is_helpdesk_visible` int NOT NULL DEFAULT '1',
  `comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `is_disaster_recovery` int NOT NULL DEFAULT '0',
  `plugin_services_servicedrtesttypes_id` int NOT NULL DEFAULT '0',
  `plugin_services_servicedrsolutiontypes_id` int NOT NULL DEFAULT '0',
  `is_disaster_recovery_documented` int NOT NULL,
  `dr_docs_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CAPEX` decimal(10,2) DEFAULT NULL,
  `OPEX` decimal(10,2) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=10439 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

**Comment by FedericoFelliny** [comment]
Hi! Sorry for the long answer. 
I managed to solve the problem. 
When I first run your script, an error appeared: "unlnown collation: 'utf8mb4_0900_ai_ci'". 
After that, I replaced all 'utf8mb4_0900_ai_ci' with 'utf8mb4_general_ci'. The script worked fine. 
The plugin started to run, but I had to create all the tables by hand. 
Thank you for your help!
